import{a as S,S as _,i as n}from"./assets/vendor-CNqCr-V-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))p(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const d of i.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&p(d)}).observe(document,{childList:!0,subtree:!0});function r(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function p(t){if(t.ep)return;t.ep=!0;const i=r(t);fetch(t.href,i)}})();const v="53386228-9ccf01ca4b721fbc8928b7547",A="https://pixabay.com/api/",O=15;async function M(e,o=1){try{return(await S.get(A,{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:O,page:o}})).data}catch(r){throw r}}const g=".gallery",P=".loader",$=".load-more",c=document.querySelector(g),l=document.querySelector(P),u=document.querySelector($),L=new _(`${g} a`,{captionsData:"alt",captionDelay:250});function q(e=[]){if(!c)return;const o=e.map(r=>`
        <li class="gallery__item">
          <a class="gallery__link" href="${r.largeImageURL}">
            <div class="photo-card">
              <img class="photo-card__img" src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
              <div class="info">
                <p class="info-item"><b>Likes</b><br>${r.likes}</p>
                <p class="info-item"><b>Views</b><br>${r.views}</p>
                <p class="info-item"><b>Comments</b><br>${r.comments}</p>
                <p class="info-item"><b>Downloads</b><br>${r.downloads}</p>
              </div>
            </div>
          </a>
        </li>
      `).join("");c.insertAdjacentHTML("beforeend",o),L.refresh()}function C(){c&&(c.innerHTML="",L.refresh())}function B(){l&&l.classList.remove("is-hidden")}function D(){l&&l.classList.add("is-hidden")}function I(){u&&u.classList.remove("is-hidden")}function m(){u&&u.classList.add("is-hidden")}const b={galleryRef:c,loaderRef:l,loadMoreRef:u},R=document.querySelector(".form"),w=document.querySelector(".form-input"),h=b.loadMoreRef,y=b.galleryRef;let a="",s=1,f=0;const T=15;(!R||!w)&&console.error("Не знайдено .form або .form-input в DOM.");R.addEventListener("submit",x);h&&h.addEventListener("click",G);async function x(e){e.preventDefault();const o=w.value.trim();if(!o){n.warning({title:"Увага",message:"Будь ласка, введіть слово для пошуку.",position:"topRight",timeout:3e3});return}o!==a&&(a=o,s=1,f=0,C(),m()),await E()}async function G(){await E(),N()}async function E(){if(a){B();try{const e=await M(a,s);if(!e||!Array.isArray(e.hits))throw new Error("Unexpected response from API");if(e.hits.length===0&&s===1){n.info({title:"Немає результатів",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:4e3}),m();return}s===1&&(f=e.totalHits||0,n.success({title:"Успіх",message:`Знайдено ${f} зображень за запитом "${a}".`,position:"topRight",timeout:3e3})),q(e.hits),(s-1)*T+e.hits.length>=f?(m(),n.info({title:"Кінець колекції",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:4e3})):(I(),s+=1)}catch(e){console.error(e),n.error({title:"Помилка",message:"Не вдалося завантажити зображення. Перевірте інтернет-зʼєднання або повторіть спробу.",position:"topRight",timeout:5e3})}finally{D()}}}function N(){if(!y)return;const e=y.querySelector(".gallery__item");if(!e)return;const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
